version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - /usr/src/app/static

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "5000:5000"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
